[versions]
# libraries
junit = "4.13.2"
javet = "4.1.7"
javenode = "0.8.0"
kotlin = "2.2.21"
kover = "0.9.1"
qodana = "2025.1.1"
jsvg = "2.0.0"
kotlin-serialization = "1.9.0"
awaitility = "4.3.0"

# plugins
changelog = "2.4.0"
intelliJPlatform = "2.7.0"

[libraries]
junit = { group = "junit", name = "junit", version.ref = "junit" }
awaitility = { module = "org.awaitility:awaitility-kotlin", version.ref = "awaitility" }
javet = { group = "com.caoccao.javet", name = "javet", version.ref = "javet" }
javet-node-windows-x86_64-i18n = { group = "com.caoccao.javet", name = "javet-node-windows-x86_64-i18n", version.ref = "javet" }
javet-node-linux-x86_64-i18n = { group = "com.caoccao.javet", name = "javet-node-linux-x86_64-i18n", version.ref = "javet" }
javet-node-macos-x86_64-i18n = { group = "com.caoccao.javet", name = "javet-node-macos-x86_64-i18n", version.ref = "javet" }
javet-node-macos-arm64-i18n = { group = "com.caoccao.javet", name = "javet-node-macos-arm64-i18n", version.ref = "javet" }
javenode = { group = "com.caoccao.javet", name = "javenode", version.ref = "javenode" }
jsvg = { module = "com.github.weisj:jsvg", version.ref = "jsvg" }
kotlinSerializationJson = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlin-serialization" }

[bundles]
javet = [
    "javet",
    "javet-node-windows-x86_64-i18n",
    "javet-node-linux-x86_64-i18n",
    "javet-node-macos-x86_64-i18n",
    "javet-node-macos-arm64-i18n",
    "javenode"
]

[plugins]
changelog = { id = "org.jetbrains.changelog", version.ref = "changelog" }
intelliJPlatform = { id = "org.jetbrains.intellij.platform", version.ref = "intelliJPlatform" }
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana" }
